module.exports = {
  content: ["_site/**/*.html", "_site/**/*.js"],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: {
    standard: [
      "hiring-banner",
      "stats-tables-container",
      "venue-stats-table",
      "class-stats-table",
      "total-row",
      "post-list",
      "post-tag",
      "proof-block",
      "proof-title",
      "proof-content",
      "proof-end",
      "definition-block",
      "definition-title",
      "definition-content",
      "theorem-block",
      "theorem-title",
      "theorem-content",
    ],
    deep: [
      /^hiring-banner/,
      /^stats-tables-container/,
      /^venue-stats-table/,
      /^class-stats-table/,
      /^post-list/,
      /^post-tag/,
      /^proof-/,
      /^definition-/,
      /^theorem-/,
    ],
  },
};
